/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { StreamService } from "../stream.service";
import { StreamCreateInput } from "./StreamCreateInput";
import { Stream } from "./Stream";
import { StreamFindManyArgs } from "./StreamFindManyArgs";
import { StreamWhereUniqueInput } from "./StreamWhereUniqueInput";
import { StreamUpdateInput } from "./StreamUpdateInput";
import { MessageFindManyArgs } from "../../message/base/MessageFindManyArgs";
import { Message } from "../../message/base/Message";
import { MessageWhereUniqueInput } from "../../message/base/MessageWhereUniqueInput";
import { PeerConnectionFindManyArgs } from "../../peerConnection/base/PeerConnectionFindManyArgs";
import { PeerConnection } from "../../peerConnection/base/PeerConnection";
import { PeerConnectionWhereUniqueInput } from "../../peerConnection/base/PeerConnectionWhereUniqueInput";

export class StreamControllerBase {
  constructor(protected readonly service: StreamService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Stream })
  async createStream(@common.Body() data: StreamCreateInput): Promise<Stream> {
    return await this.service.createStream({
      data: {
        ...data,

        user: data.user
          ? {
              connect: data.user,
            }
          : undefined,
      },
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Stream] })
  @ApiNestedQuery(StreamFindManyArgs)
  async streams(@common.Req() request: Request): Promise<Stream[]> {
    const args = plainToClass(StreamFindManyArgs, request.query);
    return this.service.streams({
      ...args,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Stream })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async stream(
    @common.Param() params: StreamWhereUniqueInput
  ): Promise<Stream | null> {
    const result = await this.service.stream({
      where: params,
      select: {
        createdAt: true,
        description: true,
        id: true,
        title: true,
        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Stream })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateStream(
    @common.Param() params: StreamWhereUniqueInput,
    @common.Body() data: StreamUpdateInput
  ): Promise<Stream | null> {
    try {
      return await this.service.updateStream({
        where: params,
        data: {
          ...data,

          user: data.user
            ? {
                connect: data.user,
              }
            : undefined,
        },
        select: {
          createdAt: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Stream })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteStream(
    @common.Param() params: StreamWhereUniqueInput
  ): Promise<Stream | null> {
    try {
      return await this.service.deleteStream({
        where: params,
        select: {
          createdAt: true,
          description: true,
          id: true,
          title: true,
          updatedAt: true,

          user: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/messages")
  @ApiNestedQuery(MessageFindManyArgs)
  async findMessages(
    @common.Req() request: Request,
    @common.Param() params: StreamWhereUniqueInput
  ): Promise<Message[]> {
    const query = plainToClass(MessageFindManyArgs, request.query);
    const results = await this.service.findMessages(params.id, {
      ...query,
      select: {
        content: true,
        createdAt: true,
        id: true,
        sentAt: true,

        stream: {
          select: {
            id: true,
          },
        },

        updatedAt: true,

        user: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/messages")
  async connectMessages(
    @common.Param() params: StreamWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        connect: body,
      },
    };
    await this.service.updateStream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/messages")
  async updateMessages(
    @common.Param() params: StreamWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        set: body,
      },
    };
    await this.service.updateStream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/messages")
  async disconnectMessages(
    @common.Param() params: StreamWhereUniqueInput,
    @common.Body() body: MessageWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      messages: {
        disconnect: body,
      },
    };
    await this.service.updateStream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/peerConnections")
  @ApiNestedQuery(PeerConnectionFindManyArgs)
  async findPeerConnections(
    @common.Req() request: Request,
    @common.Param() params: StreamWhereUniqueInput
  ): Promise<PeerConnection[]> {
    const query = plainToClass(PeerConnectionFindManyArgs, request.query);
    const results = await this.service.findPeerConnections(params.id, {
      ...query,
      select: {
        createdAt: true,
        id: true,
        status: true,

        stream: {
          select: {
            id: true,
          },
        },

        updatedAt: true,
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/peerConnections")
  async connectPeerConnections(
    @common.Param() params: StreamWhereUniqueInput,
    @common.Body() body: PeerConnectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      peerConnections: {
        connect: body,
      },
    };
    await this.service.updateStream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/peerConnections")
  async updatePeerConnections(
    @common.Param() params: StreamWhereUniqueInput,
    @common.Body() body: PeerConnectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      peerConnections: {
        set: body,
      },
    };
    await this.service.updateStream({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/peerConnections")
  async disconnectPeerConnections(
    @common.Param() params: StreamWhereUniqueInput,
    @common.Body() body: PeerConnectionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      peerConnections: {
        disconnect: body,
      },
    };
    await this.service.updateStream({
      where: params,
      data,
      select: { id: true },
    });
  }
}
